### ISSUE TITLE
Set parameter by name (shared and built in parameters are coincident)

### ISSUE THREAD

**Issue by aledarba** [DynamoDS/DynamoRevit#1383] opened 2016-11-03 09:27 UTC
## Dynamo version

1.1.0.2094

## Revit version

2017

## Operating system

Windows 10

## What did you do? 

I tried to Set.Parameter.By.Name and the name is randomly set or unset.

## What did you expect to see?

I would like to keep a consistent result, hopefully a successful result.

## What did you see instead?

The problem is that I have added a "Shared Parameter" in my project called "Category", based on NBS-CoBIE requirements. 
As you know, "Category" is a "BuiltIn" parameter defined by Revit!! Here it is!! My issue is that I would like to access to my "Shared parameter" and avoid the "BuiltIn" parameter, but when I use the predefined node Set.Parameter.By.Name, it randomly chooses one or the other and depending on that election my model is changed or not.

Do you know any way to set parameter by GUID, or to set parameters by name avoiding built in parameters? 
I am not sure about the best solution, but anything you can tell me will be very appreciated.

Thanks in advance.

**Comment by kronz** [comment] 2016-11-03 12:27
This is a duplicate of https://github.com/DynamoDS/DynamoRevit/issues/1234
Closing, but I will link back to this as it helps understand the problem.

**Closed by kronz** 2016-11-03 12:27 UTC
