### ISSUE TITLE
Sheet Setup with Views

### ISSUE THREAD

**Issue by ColinDayOrg** [DynamoDS/DynamoRevit#2193] opened 2018-10-12 14:23 UTC
<a href="https://github.com/ekatzenstein"><img src="https://avatars2.githubusercontent.com/u/6820526?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ekatzenstein](https://github.com/ekatzenstein)**
_Thursday Jul 10, 2014 at 17:28 GMT_
_Originally opened as https://github.com/DynamoDS/Dynamo/issues/1924_

----

I'm referencing Zach Kron's post on the topic: http://buildz.blogspot.com/2013/09/making-revit-views-and-sheet-layouts-in.html

The node assembly below isn't producing results though.  Is anyone able to replicate the issue?

![image](https://cloud.githubusercontent.com/assets/6820526/3542469/84618d06-0857-11e4-8e9b-4d9e012189cb.png)

**Comment by ColinDayOrg** [comment] 2018-10-12 14:23
<a href="https://github.com/riteshchandawar"><img src="https://avatars1.githubusercontent.com/u/5109531?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [riteshchandawar](https://github.com/riteshchandawar)**
_Friday Jul 11, 2014 at 08:13 GMT_

----

Can you try by providing FamilyType input directly to title block rather than using FamilySymbol.Family in between these two nodes.

**Comment by ColinDayOrg** [comment] 2018-10-12 14:23
<a href="https://github.com/ekatzenstein"><img src="https://avatars2.githubusercontent.com/u/6820526?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekatzenstein](https://github.com/ekatzenstein)**
_Friday Jul 11, 2014 at 16:31 GMT_

----

That almost worked.  Now I'm getting the error below.  I'm assuming this is due to units (which is another issue I'll post).  Regardless, some functionality for changing view scale of a create sheet would be great.  Thanks for any help.

![mode_lab_300 jul 11 12 29](https://cloud.githubusercontent.com/assets/6820526/3555573/c8871ffc-0918-11e4-979b-37098acaab23.jpg)

**Comment by ZiyunShang** [comment] 2019-09-04 07:37
Hi @ColinDayOrg ,are you still experiencing this issue now? I couldn't reproduce this on my side. Could you provide your Revit files and Dynamo files with this issue?
![D4R_Issue_2193](https://user-images.githubusercontent.com/33445445/64234941-eab74980-cf29-11e9-8154-0fd3aa3aa1c0.png)

**Comment by mjkkirschner** [comment] 2019-09-04 13:30
original issue is from @ekatzenstein

**Comment by ZiyunShang** [comment] 2020-04-20 00:44
I closed this issue, and it will be reopened when there are some new info.

**Closed by ZiyunShang** 2020-04-20 00:44 UTC
Labels: Nodes, Revit
