### ISSUE TITLE
Make warningstext selectable again

### ISSUE THREAD

**Issue by Schurkie** [DynamoDS/DynamoRevit#3097] opened 2024-10-02 12:53 UTC
### Dynamo Version

2.16

### Revit Version

2023

### Operating System

windows 11

### What did you do?

I wrote a dynamo script and got a warning message. 

### What did you expect to see?

Exactly what was expected. But it would be nice if i can select the text again in the warning to use for instance in error handling through openai

### What did you see instead?

Not selectable warning text.

### Details

![2024-10-02_14-53-18](https://github.com/user-attachments/assets/46c58894-237c-4062-8ef8-f02017f2da06)

**Comment by avidit** [comment] 2024-10-02 13:51
Duplicate of https://github.com/DynamoDS/Dynamo/issues/15441

**Closed by avidit** 2024-10-02 13:51 UTC
