### ISSUE TITLE
Revit Background Preview Bug...

### ISSUE THREAD

**Issue by Omeba720** [DynamoDS/DynamoRevit#1645] opened 2017-04-12 10:37 UTC
## Dynamo version

Dynamo version 1.3

## Revit version

Revit 2016

## Operating system

Windows 10 Professional

## What did you do? 

- Run a Dynamo script to get and set coordinate values. By getting the locations of Elements as Dynamo Points you see them in the Revit Background Preview in Revit. All gravy so far...

- I close the script and the Revit Background Preview is still showing.

- I closed and reopened the view to try force a refresh, but the blue points are still there and in all other views.

- I opened up Dynamo again (same script), run and turned the Revit Background Preview off - but the Revit Background Preview was still showing.

- I needed to print the drawing so had to close the Revit session and reopen the project as the Revit Background Preview is printable.

## What did you expect to see?

I expected the Background Preview in Revit to disappear when closing either the Active Script, or by closing the Dynamo Application.

## What did you see instead?

Background Preview in Revit remained even after closing Dynamo. needed to close Revit entirely.

## Improvement

I thought that came out of this though was perhaps a new checkbox in the Revit Print Dialog to allow transient objects generated by Dynamo's Revit Background Preview to be Plotted or not, like what's done with ref planes. it would be nice to have the option as I can see the benefit for both On/Off cases.

Cheers,
Dan woodcock

**Comment by jnealb** [comment] 2017-05-24 17:07
@kronz Ping.

**Comment by kronz** [comment] 2017-05-30 11:30
@jnealb @riteshchandawar @Omeba720  can you reproduce this in Revit 2017 or 2018?  Is this particular to Win 10?  I've not seen this before.  If anything, the Revit preview visualizations have been too transient, disappearing the moment you do anything else in the view.

**Comment by jnealb** [comment] 2017-05-30 14:14
@Omeba720 Can you please send us your dyn file? neal.burnham@autodesk.com

**Comment by Omeba720** [comment] 2017-06-08 23:15
@jnealb @riteshchandawar @kronz 

Here is a drop box of some testing files and also a video of the issue. Once Dynamo is closed the Revit model is haunted by the dead dynamo script. I tried Document.Regenerate() and UIApplication.RefreshActiveView(), some wishful thinking perhaps hoping it might force the doc/view to redraw, but this does naught to fix it. Changing views also has no effect, the Background preview still prevails and as mentioned earlier is also visible when printed.

This is using Revit 2017.1 and the issue is still present.

The background preview is also less stable than I remember in earlier builds, making small changes to the graph causes the Revit Background Preview to run for cover until you re-execute the nodes that are being previewed. Not sure if the issue is related but worth mentioning.

**here are the files**
[https://www.dropbox.com/sh/bljfaauqdu5zxqe/AACCRehy8dW5kMr10_f3reb6a?dl=0](url)

I have denuded my custom nodes as these are not on the Package Server, but I have left the clockwork nodes fully dressed as these are public.

**Comment by amontema89** [comment] 2017-07-27 17:53
I also have this issue and have seen on forums that other people have this issue. The solution is to restart Revit which is highly inefficient and would hope it was addressed officially.

**Comment by AndyDu1985** [comment] 2019-07-09 03:31
Since the file doesn't exist,https://www.dropbox.com/sh/bljfaauqdu5zxqe/AACCRehy8dW5kMr10_f3reb6a?dl=0 , close this issue. Will reopen if any new one reported.

**Closed by AndyDu1985** 2019-07-09 03:31 UTC

**Comment by ariz8workspace** [comment] 2024-04-29 12:20
Blue dots from Dynamo.
Revit 2023.1

![image](https://github.com/DynamoDS/DynamoRevit/assets/151730919/58d8f567-067b-4209-9969-1e637eba75c4)
