### ISSUE TITLE
Revit.Elements.Category.InternalCategory property is scoped as internal and is not accessable.

### ISSUE THREAD

**Issue by ScottHagie** [DynamoDS/DynamoRevit#749] opened 2015-10-29 18:53 UTC
So the internal category of the wrapped Revit category object is scoped as internal:

internal Autodesk.Revit.DB.Category InternalCategory

This makes the underlying Revit category object inaccessible to c# programs (like ZeroTouch) without using reflection or some other trickery. In contrast, the corresponding Revit.Elements.Element property, InternalElement, is scoped as public and works fine. Please change InternalCategory to public as well.

**Comment by ikeough** [comment] 2015-10-30 00:17
@ScottHagie Thanks for noticing. Actually, the `Revit.Elements.InternalElement` should be `Internal`, as the name implies. I'm not sure why this is marked public, but I'd guess it has to do with making Revit elements available to python code. We prefer not to allow direct access Revit elements created via Dynamo, as the direct access to those objects (and the ability to delete them, update them, etc.), can create unfortunate situations that side step the transaction and document modification strategies that we have in place. 

The change was made prior to the establishment of the Dynamo for github repo in 2014, so finding out exactly when and why we changed it is going to be a bit tough because the commit history before that point is lost...I think.

We do not have plans, at this time to make `Category.InternalCategory` public, and I'm going to talk to a few people on the team including @mjkkirschner and @pboyer about why we allow direct access to underlying Revit elements. Perhaps @andydandy74 has an idea as well.

**Comment by ScottHagie** [comment] 2015-10-30 03:26
I am not sure I understand. If ZeroTouch code can't access the internal Revit element to unwrap them and manipulate or read them, ZeroTouch is completely useless. Every single ZeroTouch node I have created unwraps the elements to use them, as does almost every single Python script I have seen. It is core functionality.

**Comment by andydandy74** [comment] 2015-10-30 06:31
@ikeough - There's definitely something off about ```Category``` objects, as they do not have a ```ToDSType()``` method like other Revit elements. The same goes for ```Document``` objects. It would be awesome if they behaved the same way as other Revit elements (and it would solve a number of my standing Dynamo issues). I'm not sure, though, if that deficiency is in any way connected to making the ```InternalCategory``` or ```InternalDocument``` (if that exists) public.
See https://github.com/DynamoDS/Dynamo/issues/2460 (there's a summary at the very end of the thread) for more info on my personal plight.
To give you some ideas why this might be helpful:
- In terms of Categories, it would open up the possibility to work with subcategories (query, create, assign etc.)
- In terms of Documents, it would open up the possibility to make nodes that can either accept the active document from the built-in node or linked documents from custom nodes. Since most if not all large-scale projects work with linked documents, this would go a long way towards making Dynamo more useful on such projects.

**Comment by ikeough** [comment] 2015-10-30 14:47
@ScottHagie Perhaps I'm missing the workflow you're interested in. Please provide more details.

The `InternalCategory` is marked `internal` so that access to the underlying Revit element is only available to other methods in the RevitNodes assembly. This is by design for the reasons I mention above. If you would like to propose additional functionality for the RevitNodes library, please issue a PR.

If you want to write a method that uses the `InternalCategory` from our `Revit.Elements.Category` node, then you can use the `Id` property and do a lookup in the Revit model using that id to get the Category. This is only slightly more work then using the element directly.

If you want to write a zero touch library that deals with Revit elements, there is nothing stopping you from exposing all the Revit elements that you create, and passing around "naked" Revit elements in the graph. You just won't be able to take advantage of all the functionality that we have built into `Revit.Elements.Element` for dealing with transactions.

**Comment by ksobon** [comment] 2017-05-29 22:50
I guess the answer is no, this will not be changed. @ikeough can we close this issue? 

@andydandy74 `Category` doesn't have `ToDSType()` method because it doesn't inherit from `Element` class. It's not an Element in Revit API so it should not inherit from the Element wrapper and it should not behave as Element. Same goes for `Document` object. 

Now I can understand that you want to be able to handle them in some sort of consistent manner, so I am not exactly opposed to just adding some extra functionality around these two objects specifically to make them behave kind of like Elements, but I would be careful suggesting that they should entirely behave as such. This conversation was already expanded on here: https://github.com/DynamoDS/Dynamo/issues/2460 no reason to repeat it here. Let's keep this issue to what it was originally posted by the OP.

**Comment by andydandy74** [comment] 2017-05-30 03:38
@ksobon My issues with categories are resolved. This is a rather old thread...

**Closed** 2017-05-30 14:08 UTC
