### ISSUE TITLE
Files become corrupt for no known reason

### ISSUE THREAD

**Issue by ChrisBStudio** [DynamoDS/DynamoRevit#2869] opened 2022-10-18 02:04 UTC
Hi All,

I am having issues with files becoming corrupted for no reason in Dynamo. This has happened on 2 separate occasions where I have closed the file for the day and the next day it will not open.

I am using Dynamo Revit 2.13.1.5510 and the script was created in this version as well. I have had an issue before with old packages, but I cleared all the packages and downloaded only the latest versions to get a fresh start. 

I use Dynamo a lot in our office and up until now it has been very reliable. Unfortunately if this becomes a common problem people will loose their trust in its reliability.  If some could help with some information on why this might be happening, it would be greatly appreciated.

Thankyou 

Chris

## Dynamo version

Dynamo Revit 2.13.1.5510

## Revit version

Revit 2023

## Operating system

Windows 10

## What did you do? 

Closed and reopened a script and now has an unknown error

## What did you expect to see?

The script to open as normal

## What did you see instead?

Script does not open and has unknown error

**Comment by mjkkirschner** [comment] 2022-10-18 20:24
Can you also provide one of the damaged scripts?

**Comment by ChrisBStudio** [comment] 2022-10-19 05:04
This is the error message

![image](https://user-images.githubusercontent.com/116046735/196601566-a2b63053-b544-4392-b928-e9518e8ea989.png)

And this is the script. Just change the extension to .dyn

[Step 2_New Views By Level_R23.txt](https://github.com/DynamoDS/DynamoRevit/files/9816951/Step.2_New.Views.By.Level_R23.txt)

**Comment by ChrisBStudio** [comment] 2022-10-19 05:05
Sorry hit wrong button. 

Thanks for your help

**Comment by mjkkirschner** [comment] 2022-10-24 19:29
Hi @ChrisBStudio the issue is that the file contains `"NodeLibraryDependencies": null,` I don't know how this property became null but we can make deserialization more robust, in any case to fix this file - just replace it with the following in a text editor:

`"NodeLibraryDependencies": [],`

**Comment by mjkkirschner** [comment] 2022-10-24 19:53
should be fixed after this:
https://github.com/DynamoDS/Dynamo/pull/13423

**Closed by mjkkirschner** 2022-10-24 19:53 UTC

**Comment by ChrisBStudio** [comment] 2022-10-26 02:16
You are a champion! Thankyou for your help on this, it is greatly appreciated
