### ISSUE TITLE
Strange license display in Revit

### ISSUE THREAD

**Issue by AndrewHeumann** [DynamoDS/DynamoRevit#996] opened 2016-05-17 13:43 UTC
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](http://dynamobim.org/forums/forum/dyn/), and start a thread there to discuss your issue.
## Dynamo version

1.0.0.1180
## Revit version

2015
## Operating system

Windows 7
## What did you do?

Launch Dynamo "About" window
## What did you expect to see?

![image](https://cloud.githubusercontent.com/assets/2157902/15324239/a5f9913a-1c13-11e6-8950-b309ae488e87.png)
## What did you see instead?

![image](https://cloud.githubusercontent.com/assets/2157902/15324245/ab766de0-1c13-11e6-8d4a-e4e423dc0381.png)

Possibly related to https://github.com/DynamoDS/Dynamo/issues/6631

**Comment by ThomasMahon** [comment] 2016-05-17 22:16
@AndrewHeumann shocking!

**Comment by kronz** [comment] 2016-05-17 22:31
What the *$^%$?  
Same issue of "it looks fine in Sandbox, but f-ed up in Revit"?

**Comment by ikeough** [comment] 2016-05-17 23:46
There's definitely something up with the correct styles not being applied in Revit. Our window is launched in the Revit context. We need to see if the app is able to correctly resolve the style from the Dynamo directory, or if it fails and falls back to default.

**Comment by AndrewHeumann** [comment] 2016-05-18 00:10
Yup - fine in sandbox, crazy in revit

**Comment by jnealb** [comment] 2016-05-18 00:42
But not for me with the released 1.0.0.1180 and Revit2016 on Win7, so I have to ask the question: @sharadkjaiswal could this be an install issue with Revit 2015?

**Comment by AndrewHeumann** [comment] 2016-05-18 00:54
This happens for me on 2016 as well.

**Comment by ksobon** [comment] 2016-09-01 15:05
Works fine in 1.1. @AndrewHeumann is this still an issue?

**Comment by AndrewHeumann** [comment] 2016-09-01 19:23
Yes, this is still an issue for me and @BrianRingley:
![image](https://cloud.githubusercontent.com/assets/2157902/18181195/0d02680a-7058-11e6-850d-d777f733c439.png)

**Comment by kronz** [comment] 2016-09-04 12:24
@ksobon this used to be an issue for you?  Any idea what has changed in your system setup?

**Comment by ksobon** [comment] 2016-09-04 19:03
No, i have never had that issue. I am on win 10 revit 2016/2017 at home and win 7 revit 2016/2017 at work. Never noticed this.

**Comment by ksobon** [comment] 2018-04-11 18:38
@AndrewHeumann is this still an issue? cc: @kronz can you follow up with @AndrewHeumann and get this closed? Thanks!

**Comment by AndrewHeumann** [comment] 2018-04-11 18:42
I neither own that computer nor use dynamo anymore ¯\_(ツ)_/¯

**Comment by ksobon** [comment] 2018-04-11 18:48
Stop bragging.....

Ps. Gotta escape that first backslash dude. ¯\\_(ツ)_/¯

**Comment by kronz** [comment] 2018-04-12 00:56
Sigh . . . the love is just palpable.  
Closing as "Can't reproduce"

**Closed by kronz** 2018-04-12 00:56 UTC
Labels: bug
