### ISSUE TITLE
Elemement.GetCategory behavior

### ISSUE THREAD

**Issue by DanielHurtubise** [DynamoDS/DynamoRevit#1451] opened 2017-01-13 08:26 UTC
## Dynamo version

1.2.1.3083

## Revit version

2017.1.1

## Operating system

Windows 10 x64 

## What did you do? 

I used Element.GetCategory before List.Group.ByKey and the uniques keys are not.. unique

## What did you expect to see?

To see each Category as a single value 
![pasted image at 2017_01_13 08_46 am](https://cloud.githubusercontent.com/assets/4299930/21923106/65941396-d972-11e6-98a0-ceba4d49b778.png)
for Unique Keys

## What did you see instead?

Each Category as a separate value

**Comment by ksobon** [comment] 2017-01-13 14:54
@DanielHurtubise That's happening because `Element.GetCategory` is always returning a `Category` object. Basically ALL objects on that list are `Category` and they only have a different name. To avoid confusion the Watch node is displaying `Category.Name` but the actual object is just `Category`. That makes the `GroupByKey` think that all keys are different object (each category has a different Id) and it does split them up like that. 

What you did is perfectly fine. When you extracted the name of category, and used those as keys. Now, each object on that list is a String but they are not different strings. They can be compared properly and hence you get a good result. 

I don't think there is anything to be fixed here. This is expected behavior (in my opinion at least).

**Comment by DanielHurtubise** [comment] 2017-01-13 14:55
I wouldn't dare arguing with you :)
Converting to string is not realyl a big deal either :)

Thanks for the headsup

**Comment by ksobon** [comment] 2017-01-13 14:57
If @mjkkirschner agrees with this, we can close this issue. Thanks!

**Comment by mjkkirschner** [comment] 2017-01-13 15:00
Pretty much what @ksobon said - the usual behavior of a groupBy function is to determine equality by using the objects equality method or use a function to extract a key. Equality between category wrappers is not exactly straightforward and probably why equals was not overriden to check for name. It's better to be explicit and use the name or whatever other property, category ID, etc as the key. -  I guess it could be argued we should make it easier, but, precision is good...

**Closed by mjkkirschner** 2017-01-13 15:00 UTC

**Comment by ksobon** [comment] 2017-01-13 15:06
@mjkkirschner well i didn't think of that, but we can theoretically override the `Equals` method on the `Category` class and that would fix this issue. Right? Any reasons not to override it to look at names when comparing categories? I can only think of what you mentioned above is that one user might want to compare by name and other by different property but then they can still do that explicitly extracting that info as above. We can at least have a default in that uses names.

**Comment by DanielHurtubise** [comment] 2017-01-13 15:07
I'm liking the spirit here :)

**Comment by ksobon** [comment] 2017-01-13 16:56
@mjkkirschner we can do this: 

![image](https://cloud.githubusercontent.com/assets/529781/21937935/209a5fa6-d987-11e6-8859-bbaadb22d02f.png)

by adding this to `Category` class: 

```
public override bool Equals(object obj)
        {
            var item = obj as Category;

            if (item == null)
            {
                return false;
            }
            else
            {
                return this.Name.Equals(item.Name);
            }
        }

        public override int GetHashCode()
        {
            return this.Name.GetHashCode();
        }
```

Does that work? If users wanted to do a specific comparison they still can use the method that @DanielHurtubise used in his first example.

**Comment by DanielHurtubise** [comment] 2017-01-13 16:57
Of course it works for me :)
You guys are awesome ;)

**Comment by ksobon** [comment] 2017-01-13 17:08
@DanielHurtubise i am glad you like it but we need to vet that with @mjkkirschner and rest of the team because it does change the behavior of the node quite significantly. It will behave differently with other nodes like `Equals` for example. We need to make sure that its safe to do this before we declare victory here.

**Comment by sharadkjaiswal** [comment] 2017-01-14 02:24
I think we should use category id for comparison. It would be a good idea to override Equals and GetHashCode to use id.
