### ISSUE TITLE
Delete does not work in library search

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/DynamoRevit#2939] opened 2023-08-10 01:23 UTC
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

2.18

## Revit version

2024

## Operating system

Windows 11

## What did you do? 

Tried to delete characters in the library search

## What did you expect to see?

Characters deleted

## What did you see instead?

Nothing. Only backspace works (or hitting the X icon)

**Comment by andydandy74** [comment] 2023-08-10 05:41
Duplicate of https://github.com/DynamoDS/Dynamo/issues/14089

**Comment by QilongTang** [comment] 2023-08-10 13:20
Thank you for reporting, we are working on this fix now actually, see progress at https://github.com/DynamoDS/Dynamo/pull/14217

**Closed** 2023-08-10 13:21 UTC
