### ISSUE TITLE
Round Trip from 2019 to 2020 to 2019

### ISSUE THREAD

**Issue by DanielHurtubise** [DynamoDS/DynamoRevit#2426] opened 2019-09-03 17:48 UTC
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo 2.0.3 on Revit 2019
Dynamo Core 2.2.1 on Revit 2020
Dynamo Revit 2.1.0 on Revit 2020

## Revit version

Revit 2019.2.2
Revit 2020.1

## Operating system

Windows 10 build 1903

## What did you do? 

Create a definition in 2019, opened it in 2020, saved it, reopen in 2019 and only the Code Block is still in the definition.

## What did you expect to see?

See all my nodes again

## What did you see instead?

Lost all the nodes

See this video https://www.dropbox.com/s/3twu4qfhhx6c88k/Roundtrip%20Issue.mp4?dl=0

**Comment by ZiyunShang** [comment] 2019-09-04 07:13
Hi @DanielHurtubise , I can't reproduce this issue with Dynamo 2.0.3 on Revit 2019 and Dynamo2.2.1 on
 Revit 2020. I found that your DynamoCore & DynamoRevit on Revit 2020 have different version. Could you align them and try again?

**Comment by mjkkirschner** [comment] 2019-09-04 12:51
Yes curious how did you update your core version ?

**Comment by ZiyunShang** [comment] 2020-04-20 00:42
I closed this issue, and it will be reopened when there are some new info.

**Closed by ZiyunShang** 2020-04-20 00:42 UTC
